name: Scrape Talk Locations

on:
  push:
    paths:
      - 'talks/**'
      - 'talkmap.ipynb'

permissions:
  contents: write  # Grants push permissions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0  # 📌 Full history to allow rebasing

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install jupyter pandas requests beautifulsoup4 geopy getorg

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute talkmap.ipynb \
            --output talkmap_out.ipynb

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote set-url origin \
            https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}

          git add talkmap_out.ipynb
          git commit -m "Automated update of talk locations" || echo "No changes to commit"

          # 🌀 Sync with remote to resolve non-fast-forward  
          git fetch origin
          git pull --rebase origin "${GITHUB_REF##*/}"

          git push origin HEAD:"${GITHUB_REF##*/}"
